### ISSUE TITLE
Configuration path on different platforms

### ISSUE THREAD

**Issue by LinusU** [rvagg/ghauth#14]
Hi @rvagg,

I wrote a small library to store small config files for node.js application in the correct platform for the current platform. Currently you always store them in `$HOME/.config/<name>` which only is correct on some Linux distributions.

If you think that it's interesting I can submit a pull request for you, it should be a quite small change.

https://github.com/LinusU/node-application-config

**Comment by rvagg** [comment]
@LinusU that's actually pretty neat, is the windows support consistent for all recent versions of windows?

I'd accept a PR for this, but stick to `~` for the semver range when you do. Cheers.

**Comment by LinusU** [comment]
I haven't tried it on Windows 10 but I think that it should be correct. It seems like the newer versions of windows exposes `LOCALAPPDATA`.

I'll send you a pull request :)

**Comment by bcomnes** [comment]
This is done
