### ISSUE TITLE
Missing 'notifications' scope

### ISSUE THREAD

**Issue by RichardLitt** [rvagg/ghauth#18]
I am trying to use ghauth with this config setting, [here](https://github.com/RichardLitt/ignore-github-users/blob/feature/add-ghauth/cli.js#L11):

```js
const authOptions = {
  configName: 'ghauth',
  note: 'Ignore GitHub notifications for a specific user',
  userAgent: 'ignoreGithubUsers',
  scopes: ['notifications']
}
```

However, I am running into this error:

 ```js
{ [Error: {"message":"Missing the 'notifications' scope.","documentation_url":"https://developer.github.com/v3"}]
  status: 403,
  json: 
   { message: 'Missing the \'notifications\' scope.',
     documentation_url: 'https://developer.github.com/v3' } }
```

Any ideas why this is happening? I have the scope set right.

**Comment by rvagg** [comment]
You set this scope before you first ran `ghauth` the first time? Perhaps try removing the config file and the token in your github account.

https://github.com/settings/tokens lists all of your personal tokens btw, it should show the scopes that have been set on each token.

**Comment by RichardLitt** [comment]
Where is the config stile stored? I'm not sure what is meant by "user's config directory". Thanks.

**Comment by RichardLitt** [comment]
Nevermind, got it. You're right, deleting the config file and resetting it worked. 

Thank you!
