### ISSUE TITLE
Add option to define replaced character when echoing password

### ISSUE THREAD

**Issue by jleft** [rvagg/ghauth#20]
It would be nice if the `options` argument had an optional property which would make it possible to define the character used to replace each password character when echoing.

For example, setting it to `*`, would result it output like this:

```
Your GitHub password: ********
```

Setting to an empty string (or another falsy value) could disable the replacement but still silence the output:

```
Your GitHub password:
```

It could default to `✔` for backwards-compatiblility.

I'm happy to open a PR if this is something which would be welcome? 😃

**Comment by bcomnes** [comment]
See `options.passwordReplaceChar`
