### ISSUE TITLE
Depreciated OAuth Authorization API

### ISSUE THREAD

**Issue by bcomnes** [rvagg/ghauth#26]
Hey just looking into the following emails I've been getting after using ghauth powered clis.  

> 
> You or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent gh-release.
> 
> We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
> 
> You can learn more about these changes by visiting our developer blog:
> https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/

Looks like this wonderfully convenient API is deprecated in favor of some kind of oauth web flow.  

https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/
https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
https://docs.github.com/en/developers/apps/authorizing-oauth-apps#device-flow

Any plans to move this library over to that flow? Or do you recommend a different library that covers that?  Interested in a PR that moves over to that auth flow?

**Comment by rvagg** [comment]
🤦 what a mess, so we're going to need to get a user's browser involved now for this to work. Yeah I'd look at a PR that dealt with that, there's a lot that depends on this library working and even the brownouts they're talking about are going to be annoying. This must be why the new `gh` tool from GitHub has a terrible auth experience. Thanks for raising this, I wasn't aware of it.

**Comment by bcomnes** [comment]
The good news is device flow is supported, so browser redirects are not necessary, cli can poll a url while a user enters some code on a website. 

I also believe existing tokens will still work, they are just PATs. 

New tokens are not pats but application tokens, but still work similarly if I understand correctly. 

I’ll see what I can whip up.
